### PR TITLE
Feat: view nft details

### LINKED ISSUE #37: [Subtask]: Asset management: View NFT details

### PR DESCRIPTION
**Pull request by cpl121**
Fixes #37

- The carousel was not loaded when uploading the cache file in inspect candy machine

## Changes

  - Click image in view collection to view nft details
  - Improved carousel layout
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

### CODE REVIEW

**Review by agus-xyz — COMMENTED** [review]
for me, the new feature does not seem to work. The view of the collection seems broken (no NFTs are shown), and I cannot click to see the details or see the next NFT.

image

**Comment by agus-xyz** [comment]
oh, ok, I think if I scroll horizontally I find the elements... 😅 

image
image
image

**Comment by cpl121** [comment]
It should be fixed @agus-xyz

**Review by agus-xyz — APPROVED** [review]
It works!

**Pull request merged**
