### PR TITLE
Feat: Add collection

### LINKED ISSUE #38: [Subtask]: Asset management: Add collection

### LINKED ISSUE #83: [Task]: Add mint button

### PR DESCRIPTION
**Pull request by cpl121**
Fixes #83 
Fixes #38 

## Changes

  - Check how many nfts are left to mint
  - Add a button to mint 1 token in the verify page
  
### Checks

* [X] Have you catchup your branch with the latest state in base?
* [X] Have you lint your code locally prior to submission?
* [X] Have you reviewed your proposed changes and removed debris?
* [X] Have you successfully ran due tests with your changes?

### CODE REVIEW

**Review by aspnxdd — CHANGES_REQUESTED** [review]

**Comment by agus-xyz** [comment]
@cpl121 any idea why the preview is failing?

**Comment by cpl121** [comment]
Build solved and merge done @begonaalvarezd

**Review by agus-xyz — COMMENTED** [review]
I generally would disagree with the nomenclature of calling `token` to an `nft` within the code, unless the specific code is really agnostic to any kind of token. But we definitely should not use the nomenclature `token` in the UI, and definitely not mixing both nomenclatures "token" and "nft" indistinctively.

**Review by agus-xyz — APPROVED** [review]
it works

**Pull request merged**
